### ISSUE TITLE
JS error for second socket call w/o callback

### ISSUE THREAD

**Issue by luposlip** [enterlab/rente#2]
The second time - and only the second time - the socket returns data in the case without a callback, it fails with the following message:

```
Uncaught Error: nth not supported on this type cljs.core/Keyword
```

**Comment by tuhlmann** [comment]
@luposlip Are there any news regarding this bug? It seems I only get this bug for the first event, all subsequent events work without problems.

Thanks,
Torsten.

**Comment by brandonparsons** [comment]
:+1: 

Putting my name down here so i get notified when this gets figured out. I'm seeing the same error!

**Comment by luposlip** [comment]
Hi guys,

I haven't spent any time to investigate this.
If one of you have the time to look more into it, I'd appreciate.

Otherwise we may see what ptaossanis says. I'll get more time to investigate in April, if nothing happens before that.

Best,
Henrik

**Comment by tuhlmann** [comment]
I found the problem!

I replied on Sente's github: https://github.com/ptaoussanis/sente/issues/115#issuecomment-84039949

In short, its that second go-loop in app.cljs. @luposlip What's the reason for this loop? I would think firing off the Sente router does already establish the correct loop?

Any, removing that loop everything worked...

**Comment by luposlip** [comment]
You're right, it works!
I'll be committing the fixed app later today.

I don't remember the reasoning behind this go-loop 8-/

Thanks for your input @tuhlmann! :-)
