### ISSUE TITLE
Heroku config

### ISSUE THREAD

**Issue by okjulian** [enterlab/rente#5]
Hi there,

Just wanted to let you know that in order to successfully deploy rente to heroku I had to add two small details, but without them things did not work:
- Added `:min-lein-version "2.0.0"` to  `project.clj`
- Replaced `:rente-port` with `:port` in `config.clj`

Cheers!

**Comment by luposlip** [comment]
I'm not sure why it has worked for me earlier. But I couldn't get it to work either, so included your changes.

To make it as easy as possible for anyone to deploy it in the future, I've also added a Heroku deploy button to the README.

Thanks for your input! :+1:

**Comment by okjulian** [comment]
Thank you for fixing this so quickly!
