### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by ioRekz** [enterlab/rente#7]
Hi, I'm trying to deploy my app on heroku but can't manage to do it.

If I clone this repo, run the config:add command and push, this is what I get :
- Web process failed to bind to $PORT within 60 seconds of launch

Am I missing something ?

**Comment by luposlip** [comment]
Hi Jeremy,

To be honest I didn't try the "manual" deployment after my last commit.
But the "Deploy to Heroku" button works fine for me. Have you tried that?

Best,
Henrik

**Comment by ioRekz** [comment]
Yes the button works. I don't understand what is the diff between the 2
methods.
My app is on heroku only so I guess I can't use the button.

**Comment by ioRekz** [comment]
I managed to run the app by adding 
:min-lein-version "2.5.0" to the project.clj

and using the (env :port) instead of rente-port so the server use the port provided by heroku

I'm not sure that the min version did something but heroku was using lein 1.7 so I guess it's better anyway. I can make a pull request if those change seems relevant for everybody

**Comment by luposlip** [comment]
These updates of min-lein-version and :port was pushed the 25th of March. Please pull or re-clone, and test again. If it works for you out of the box afterwards, I'll close this issue.
