### ISSUE TITLE
figwheel warns on single segment name

### ISSUE THREAD

**Issue by Tyler-Anderson** [enterlab/rente#8]
in start.cljs the single segment namespace "start" triggers figwheel's warning keeping it from updating. 
![screen shot 2015-05-05 at 12 07 26 pm](https://cloud.githubusercontent.com/assets/1096058/7480725/61edf602-f31f-11e4-903c-8bfc183f476a.png)

**Comment by luposlip** [comment]
Yes, you're right. But since it's only start.cljs and that ns is only meant for actually starting the app, I don't see it as an actual issue.

Of course you're free to put start into rente.start. If you do, and submit a pull request, I'll be happy to integrate it! :-)

**Comment by luposlip** [comment]
Fixed with Pull Request #9 from @Tyler-Anderson.
